# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Learning Stripe SDK' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Learning Stripe SDK
    pod 'Stripe'

  target 'Learning Stripe SDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Learning Stripe SDKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
